### Lista de Tarefas
GET http://localhost:5231/api/tarefas

### Cadastrar Tarefa
POST http://localhost:5231/api/tarefas
Content-Type: application/json

{
    "Id":"2", 
    "StatusId":"1",
    "Titulo":"Ads",
    "DataVencimento":"2222-05-05"
}

###Buscando por Id
GET http://localhost:5231/api/tarefas/1

### Cadastrar Tarefa
PUT http://localhost:5231/api/tarefas/2
Content-Type: application/json

{ 
    "StatusId":"2",
    "Titulo":"Aadaaaaaads",
    "DataVencimento":"5552-05-05"
}
